# This file is part of mysql-db-backup-faster.
# https://github.com/heynemann/generator-python-package

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2020, gwangil <pki054@naver.com>

language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
